const labels: Record<string, string> = {
  online: "Online",
  presencial: "Presencial",
  hibrido: "Híbrido",
  publicada: "Publicada",
  publicado: "Publicado",
  rascunho: "Rascunho",
  arquivado: "Arquivado",
  encerrada: "Encerrada",
  cancelada: "Cancelada",
  inscrito: "Inscrito",
  cancelado: "Cancelado",
  agendado: "Agendado",
  concluido: "Concluído",
  expirado: "Expirado",
  removido: "Removido",
  ativo: "Ativo",
  inativo: "Inativo",
  previsto: "Previsto",
  realizado: "Realizado",
  presente: "Presente",
  ausente: "Ausente",
  justificado: "Justificado",
  link: "Link",
  pdf: "PDF",
  video: "Vídeo",
  apresentacao: "Apresentação",
  documento: "Documento",
  planilha: "Planilha",
  imagem: "Imagem",
  texto: "Texto complementar",
  referencia: "Referência",
  publico: "Público",
  inscritos: "Inscritos",
  interno: "Interno",
  pendente: "Pendente",
  "pendente emissao": "Pendente de emissão",
  disponivel: "Disponível",
  valido: "Válido",
  oculto: "Oculto",
  course_opened: "Curso acessado",
  course_started: "Curso iniciado",
  lesson_opened: "Aula acessada",
  lesson_completed: "Aula concluída",
  material_opened: "Material acessado",
  forum_posted: "Participação no fórum",
  certificate_requested: "Certificação solicitada",
  aula: "Aula",
  atividade: "Atividade",
  prazo: "Prazo",
  encontro_presencial: "Encontro presencial",
  encontro_online: "Encontro online",
  forum_debate: "Fórum/debate",
  certificacao: "Certificação",
  reuniao: "Reunião",
  evento_institucional: "Evento institucional",
  compromisso_pessoal: "Compromisso pessoal",
  scheduled: "Agendado",
  completed: "Concluído",
  cancelled: "Cancelado",
  private: "Privado",
  course: "Curso",
  class: "Turma",
  institutional: "Institucional",
  manual: "Manual",
  lesson: "Aula",
  activity: "Atividade",
  certificate: "Certificado",
  external: "Externo",
  none: "Sem integração",
  google: "Google Calendar (simulado)",
  outlook: "Outlook/Microsoft 365 (simulado)",
  apple: "Apple Calendar via .ics",
  ics: "Arquivo .ics",
  export_only: "Somente exportação",
  import_only: "Somente importação",
  two_way: "Sincronização bidirecional",
  "agenda.evento_criado": "Evento de agenda criado",
  "agenda.evento_editado": "Evento de agenda editado",
  "agenda.evento_cancelado": "Evento de agenda cancelado",
  "agenda.evento_excluido": "Evento de agenda excluído",
  "agenda.integracao_configurada": "Integração da agenda configurada",
  "convite.criado": "Link de cadastro criado",
  "convite.administrador_criado": "Link administrativo criado",
  "convite.revogado": "Link de cadastro revogado",
  "convite.usado": "Link de cadastro utilizado",
  "convite.tentativa_bloqueada": "Tentativa bloqueada de uso de link",
  "usuario.criado_convite": "Usuário cadastrado por convite",
  "curso.criado": "Curso criado",
  "curso.editado": "Curso editado",
  "curso.publicado": "Curso publicado",
  "curso.arquivado": "Curso arquivado",
  "turma.criada": "Turma criada",
  "turma.editada": "Turma editada",
  "turma.publicada": "Turma publicada",
  "turma.instrutor_atualizado": "Instrutor da turma atualizado",
  "instrutoria.vinculo_criado": "Instrutor vinculado à turma",
  "instrutoria.vinculo_encerrado": "Vínculo de instrutoria encerrado",
  "instrutoria.concluida_automatica": "Vínculo encerrado por conclusão da turma",
  "instrutoria.expirada_automatica": "Vínculo de instrutoria expirado",
  "instrutoria.cancelada_automatica": "Vínculo encerrado por cancelamento da turma",
  "instrutoria.acesso_negado_sem_vinculo": "Acesso negado sem vínculo ativo",
  "material.criado": "Material criado",
  "material.editado": "Material editado",
  "material.publicado": "Material publicado",
  "material.ocultado": "Material ocultado",
  "material.excluido": "Material excluído",
  "material.acesso_negado_sem_vinculo": "Acesso negado a material sem vínculo ativo",
  "inscricao.criada": "Inscrição criada",
  "inscricao.autoinscricao": "Autoinscrição realizada",
  "inscricao.link_publico": "Inscrição por link público",
  "inscricao.cancelada_participante": "Inscrição cancelada pelo aluno",
  "presenca.registrada": "Presença registrada",
  "certificado.conclusao_aprovada": "Conclusão aprovada e certificado emitido",
  "certificado.cancelado": "Certificado cancelado",
  "avaliacao.turma_respondida": "Avaliação da turma respondida",
  "avaliacao.aluno_instrutor_salva": "Avaliação do aluno salva",
  "avaliacao.requisitos_certificacao_alterados": "Requisitos de certificação alterados",
  "questionario.criado": "Questionário criado",
  "questionario.publicado": "Questionário publicado",
  "questionario.respondido": "Questionário respondido",
  "perfil.criado": "Perfil criado",
  "perfil.permissoes_alteradas": "Permissões do perfil alteradas",
  "perfil.excluido": "Perfil excluído",
  "usuario.criado": "Usuário criado",
  "usuario.ativo": "Usuário ativado",
  "usuario.inativo": "Usuário inativado",
  "usuario.perfis_alterados": "Perfis do usuário alterados",
  "usuario.senha_redefinida": "Senha redefinida",
  "usuario.lattes_atualizado": "Currículo Lattes atualizado",
  "forum.topico_criado": "Tópico de fórum criado",
  "demo.seed": "Dados de demonstração preparados",
  administrador_geral: "Administrador",
  gestor_labc: "Gestor LaBC",
  instrutor: "Instrutor",
  participante: "Aluno",
  moderador: "Moderador",
  convidado: "Convidado",
  active: "Ativo",
  expired: "Expirado",
  revoked: "Revogado",
  used: "Usado",
  limit_reached: "Limite atingido",
  coordenador_curso: "Coordenador de curso",
  moderador_forum: "Moderador de fórum",
  gestor_certificados: "Gestor de certificados",
  apoio_administrativo: "Apoio administrativo",
  avaliador: "Avaliador",
  cursos: "Cursos",
  turmas: "Turmas",
  inscricoes: "Inscrições",
  presencas: "Registros de frequência",
  certificados: "Certificados",
  perfis: "Perfis",
  usuarios: "Usuários",
  topicos: "Tópicos",
  comentarios: "Comentários",
  foruns: "Fóruns",
  sistema: "Sistema"
};

export function uiLabel(value: string | null | undefined) {
  if (!value) {
    return "-";
  }

  return labels[value] ?? value;
}
